Add link to developer/GH info in Admin dropdown
ucsb-cs156-w24/proj-courses-w24-5pm-1 pull request #26
Opened 2024-02-27 00:57 UTC by TantaiYanhen

In this PR, we add an item in the Admin dropdown called "Developer Info", which would navigate us to `\developer`, the developer page.

<img width="1201" alt="截屏2024-02-26 下午4 00 20" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/assets/124806197/0d4296ce-377a-4e8f-b413-ed5eab1983ff">

2024-02-29 00:12 UTC, tallyhawley requested changes
Could you include a link to your Dokku deployment showing these changes if possible?

2024-03-01 01:10 UTC, tallyhawley commented on .gitignore
>  .vscode/
Why are we pushing changes to .gitignore?

2024-03-04 22:21 UTC, tallyhawley approved these changes

2024-03-06 02:01 UTC, winzuo approved these changes
LGTM.

2024-03-06 02:05 UTC, merged