FEATURE: More descriptive error message on personal schedule and Button!
ucsb-cs156-w24/proj-courses-w24-5pm-1 pull request #31
Opened 2024-02-28 23:13 UTC by El-Beetor

Added a more descriptive error message for when a user tries to add a course to their schedule but they 
did not include a schedule. 

I also created a button that links to the create schedule page.(for the bonus)

<img width="497" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/assets/91820969/a5011d53-4848-466b-a17c-58b63e6629de">

closes #22

2024-03-01 02:31 UTC, tallyhawley requested changes
Dokku link?

2024-03-07 01:10 UTC, El-Beetor commented
Dokku Link: https://project-el-beetor.dokku-05.cs.ucsb.edu/

2024-03-07 02:23 UTC, tallyhawley requested changes
This error message shouldn't display on ALL errors. Only on the error of "No personal schedule". 

This is not the expected behavior:
<img width="731" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/assets/20908336/b5d1b6a8-375d-446c-bf1e-d59278cb72f0">

I should get the existing `mutation.error.response.data?.message` which references an invalid enroll code.

2024-03-07 06:36 UTC, El-Beetor commented
Try it again. Changed the error handling
<img width="797" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-1/assets/91820969/e5f2671e-80b6-4941-861c-ec9faacd4545">

2024-03-07 23:53 UTC, tallyhawley requested changes
Looks good other than the typo, just fix that and you'll be good to merge :)

2024-03-07 23:53 UTC, tallyhawley commented on frontend/src/main/pages/Courses/PSCourseCreatePage.js
> +      mutation.error.response.data?.message || "Unkown Error";
typo

2024-03-07 23:59 UTC, tallyhawley approved these changes
Looks good to me

2024-03-08 01:07 UTC, Bravo-Luis approved these changes
LGTM!

2024-03-08 01:14 UTC, merged